requests.exceptions.ConnectionError: HTTPConnectionPool(host='gutenb.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feec207a880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7feec207a880>: Failed to establish a new connection: [Errno -2] Name or service not known

raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='gutenb.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feec207a880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='gutenb.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feec207a880>: Failed to establish a new connection: [Errno -2] Name or service not known'))


errors.append('Unable to get URL. Make sure it exists.\n' + ex)
TypeError: can only concatenate str (not "ConnectionError") to str

{'errors': [
'Unable to get URL. Make sure it exists. 
404 Client Error: NOT FOUND for url: https://httpbin.org/status/404'
]
},
'param_1': 1}
